export const dummy_user = [
  {
    id: 1,
    name: '이가연',
    nickname: '테디베어1',
    profileImage: require('./assets/images/dummy/dummyProfile_1.png'),
    email: 'test1@test.com',
    password: 'password',
    bookmarkList: [2, 3, 5, 6, 7],
    interestArea: 'japan',
  },
  {
    id: 2,
    name: '오정혁',
    nickname: '테디베어2',
    profileImage: require('./assets/images/dummy/dummyProfile_2.png'),
    email: 'test2@test.com',
    password: 'password',
    bookmarkList: [2, 3, 5, 6, 7],
    interestArea: 'japan',
  },
  {
    id: 3,
    name: '우예인',
    nickname: '테디베어3',
    profileImage: require('./assets/images/dummy/dummyProfile_3.png'),
    email: 'test3@test.com',
    password: 'password',
    bookmarkList: [2, 3, 5, 6, 7],
    interestArea: 'japan',
  },
  {
    id: 4,
    name: '한서흔',
    nickname: '테디베어4',
    profileImage: require('./assets/images/dummy/dummyProfile_4.png'),
    email: 'test4@test.com',
    password: 'password',
    bookmarkList: [2, 3, 5, 6, 7],
    interestArea: 'japan',
  },
  {
    id: 5,
    name: '김동영',
    nickname: '테디베어8',
    profileImage: require('./assets/images/dummy/dummyProfile_5.png'),
    email: 'test5@test.com',
    password: 'password',
    bookmarkList: [2, 3, 5, 6, 7, 'UyuoGU8kAwfZpj0fVdgq', 'byCQ6rLvv2WG64CdJ6HB'],
    interestArea: 'japan',
  },
  {
    id: 6,
    name: '김민주',
    nickname: '마루마루6',
    profileImage: require('./assets/images/dummy/dummyProfile_6.png'),
    email: 'test6@test.com',
    password: 'password',
    bookmarkList: [2, 3, 5, 6, 7],
    interestArea: 'japan',
  },
];

export const dummy_article = [
  {
    id: 1,
    title: '도쿄 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요? 안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요? 안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들',
    createdAt: new Date().getTime(),
    liked: 1,
    bookmarked: 1,
    creator: 5,
    tag: '질문',
    comments: [],
    images: [],
  },
  {
    id: 2,
    title: '프랑스 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 프랑스에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-05-03 10:20').getTime(),
    liked: 2,
    bookmarked: 2,
    creator: 2,
    tag: '잡담',
    comments: [],
    images: [],
  },
  {
    id: 3,
    title: '미국 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 미국에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-05-02 10:20').getTime(),
    liked: 3,
    bookmarked: 3,
    creator: 4,
    tag: '질문',
    comments: [],
    images: [],
  },
  {
    id: 4,
    title: '독일 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 독일에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-05-01 10:20').getTime(),
    liked: 4,
    bookmarked: 4,
    creator: 3,
    tag: '질문',
    comments: [],
    images: [],
  },
  {
    id: 5,
    title: '호주 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 호주에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-04-15 10:20').getTime(),
    liked: 5,
    bookmarked: 5,
    creator: 4,
    tag: '질문',
    comments: [],
    images: [],
  },
  {
    id: 6,
    title: '호주 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 호주에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-04-21 10:20'),
    liked: 5,
    bookmarked: 5,
    creator: 5,
    tag: '질문',
    comments: [],
    images: [],
  },
  {
    id: 7,
    title: '호주 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 호주에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-04-20 10:20'),
    liked: 5,
    bookmarked: 6,
    creator: 5,
    tag: '질문',
    comments: [],
    images: [],
  },
  {
    id: 8,
    title: '호주 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 호주에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-04-20 10:20'),
    liked: 5,
    bookmarked: 6,
    creator: 5,
    tag: '질문',
    comments: [],
    images: [],
  },
  {
    id: 9,
    title: '호주 3박 4일 계획표 평가 부탁드려요!',
    contents:
      '안녕하세요! 제가 다음 달에 처음으로 호주에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-04-20 10:20'),
    liked: 5,
    bookmarked: 6,
    creator: 5,
    tag: '질문',
    comments: [],
    images: [],
  },
];

export const dummy_comment = [
  {
    id: 1,
    name: '도쿄타워',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요?',
    like: 1,
    userId: 1,
    createdAt: new Date('2024-05-12 10:10'),
  },
  {
    id: 2,
    name: '도쿄타워',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요??',
    like: 5,
    userId: 1,
    createdAt: new Date('2024-05-12 10:20'),
  },
  {
    id: 3,
    name: '도쿄타워',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 1,
    createdAt: new Date('2024-05-14 16:20'),
  },
  {
    id: 4,
    name: '도쿄타워',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 1,
    createdAt: new Date('2024-05-14 16:20'),
  },
  {
    id: 5,
    name: '김동영',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 5,
    createdAt: new Date('2024-05-14 16:20'),
  },
  {
    id: 6,
    name: '김동영',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 5,
    createdAt: new Date('2024-05-15 16:20'),
  },
  {
    id: 7,
    name: '김동영',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 5,
    createdAt: new Date('2024-05-16 16:20'),
  },
  {
    id: 8,
    name: '김동영',
    articleId: 1,
    contents: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 5,
    createdAt: new Date('2024-05-17 16:20'),
  },
];

export const dummy_meet = [
  {
    id: 1,
    location: { latitude: 37.78827, longitude: -122.4322 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    name: '도쿄최고',
    userId: 4,
    profileImage: require('./assets/images/dummy/dummyProfile_1.png'),
    category: 'impromptu',
    createAt: new Date().getTime(),
    meetingAt: new Date().getTime(),
  },
  {
    id: 2,
    location: { latitude: 37.78825, longitude: -122.4324 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    name: '도쿄최고',
    profileImage: require('./assets/images/dummy/dummyProfile_2.png'),
    category: 'impromptu',
    createAt: new Date().getTime(),
    meetingAt: new Date().getTime(),
  },
  {
    id: 3,
    location: { latitude: 37.7883, longitude: -122.432 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    userId: 4,
    profileImage: require('./assets/images/dummy/dummyProfile_3.png'),
    name: '도쿄최고',
    category: 'accompany',
    createAt: new Date().getTime(),
    meetingAt: new Date().getTime(),
  },
  {
    id: 4,
    location: { latitude: 37.78815, longitude: -122.4318 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    name: '도쿄최고',
    userId: 4,
    profileImage: require('./assets/images/dummy/dummyProfile_4.png'),
    category: 'impromptu',
    createAt: new Date().getTime(),
    meetingAt: new Date().getTime(),
  },
];

export const dummy_chat = [
  {
    id: 1,
    sendUserId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
    receiveUserId: 4,
    chatList: [
      {
        id: 1,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:20').getTime(),
        isRead: true,
      },
      {
        id: 2,
        userId: 4,
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:21').getTime(),
        isRead: true,
      },
      {
        id: 3,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-12 10:22').getTime(),
        isRead: true,
      },
      {
        id: 4,
        userId: 4,
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-12 10:23').getTime(),
        isRead: true,
      },
      {
        id: 5,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-12 10:24').getTime(),
        isRead: false,
      },
    ],
  },
  {
    id: 2,
    sendUserId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
    receiveUserId: 3,
    chatList: [
      {
        id: 1,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:20').getTime(),
        isRead: true,
      },
      {
        id: 2,
        userId: 3,
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:21').getTime(),
        isRead: true,
      },
      {
        id: 3,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-12 10:22').getTime(),
        isRead: true,
      },
      {
        id: 4,
        userId: 3,
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-12 10:23').getTime(),
        isRead: true,
      },
      {
        id: 5,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-12 10:24').getTime(),
        isRead: true,
      },
    ],
  },
  {
    id: 3,
    sendUserId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
    receiveUserId: 2,
    chatList: [
      {
        id: 1,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:20').getTime(),
        isRead: true,
      },
      {
        id: 2,
        userId: 2,
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:21').getTime(),
        isRead: true,
      },
      {
        id: 3,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-12 10:22').getTime(),
        isRead: true,
      },
      {
        id: 4,
        userId: 2,
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-12 10:23').getTime(),
        isRead: true,
      },
      {
        id: 5,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-12 10:24').getTime(),
        isRead: true,
      },
      {
        id: 6,
        userId: 2,
        text: '네 좋아요!',
        createdAt: new Date('2024-05-13 10:10').getTime(),
        isRead: true,
      },
      {
        id: 7,
        userId: 2,
        text: '뭔가 긴글이 필요할 것 같아 이렇게 남겨보는 텍스트입니다!',
        createdAt: new Date('2024-05-13 10:10').getTime(),
        isRead: true,
      },
    ],
  },
  {
    id: 4,
    sendUserId: 1,
    receiveUserId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
    chatList: [
      {
        id: 1,
        userId: 1,
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:20').getTime(),
        isRead: true,
      },
      {
        id: 2,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '안녕하세요',
        createdAt: new Date('2024-05-12 10:21').getTime(),
        isRead: true,
      },
      {
        id: 3,
        userId: 1,
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-12 10:22').getTime(),
        isRead: true,
      },
      {
        id: 4,
        userId: 'f1ace8fb-d081-40ae-ab9b-b6002b8c0d06',
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-12 10:23').getTime(),
        isRead: true,
      },
      {
        id: 5,
        userId: 1,
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-12 10:24').getTime(),
        isRead: false,
      },
    ],
  },
];

export const dummyPlans = [
  {
    id: '1',
    title: '싱가포르 여행',
    dates: ['24.05.20', '24.05.28'],
    location: '싱가포르',
    tags: ['싱가포르', '자유여행'],
    friendList: [
      { friendId: 1, name: '오정혁' },
      { friendId: 2, name: '우예인' },
      { friendId: 3, name: '한서흔' },
    ],
    coverImage: require('./assets/images/myTrip/basicimage1.jpeg'),
  },
  {
    id: '2',
    title: '도쿄 여행',
    dates: ['24.05.17', '24.05.20'],
    location: '도쿄, 일본',
    tags: ['도쿄', '디즈니랜드', '맛집탐방'],
    friendList: [
      { friendId: 1, name: '오정혁' },
      { friendId: 2, name: '우예인' },
    ],
    coverImage: require('./assets/images/myTrip/basicimage2.jpeg'),
  },
  {
    id: '3',
    title: '벨기에 여행',
    dates: ['24.05.10', '24.05.16'],
    location: '벨기에, 브뤼셀',
    tags: ['와플', '유럽여행'],
    friendList: [
      { friendId: 1, name: '오정혁' },
      { friendId: 2, name: '우예인' },
      { friendId: 3, name: '한서흔' },
    ],
    coverImage: require('./assets/images/myTrip/basicimage3.jpeg'),
  },
  {
    id: '4',
    title: '홍콩 여행',
    dates: ['24.05.10', '24.05.16'],
    location: '마카오, 홍콩',
    tags: ['카지노', '찐맛집'],
    friendList: [
      { friendId: 1, name: '오정혁' },
      { friendId: 2, name: '우예인' },
      { friendId: 3, name: '한서흔' },
    ],
    coverImage: require('./assets/images/myTrip/basicimage4.jpeg'),
  },
];

export const dummy_locations = [
  {
    locationId: 1,
    locationName: '도쿄 타워',
    locationAddress: '4-chome 2-8, Shibakoen, Minato 105-0011 Tokyo Prefecture',
    isFavorite: true,
  },
  {
    locationId: 2,
    locationName: '도쿄 디즈니랜드',
    locationAddress: '4-chome 2-8, Shibakoen, Minato 105-0011 Tokyo Prefecture',
    isFavorite: true,
  },
  {
    locationId: 3,
    locationName: '이치란 라멘',
    locationAddress: '4-chome 2-8, Shibakoen, Minato 105-0011 Tokyo Prefecture',
    isFavorite: false,
  },
  {
    locationId: 4,
    locationName: '타코야키',
    locationAddress: '4-chome 2-8, Shibakoen, Minato 105-0011 Tokyo Prefecture',
    isFavorite: true,
  },
  {
    locationId: 5,
    locationName: '디즈니스토어',
    locationAddress: '4-chome 2-8, Shibakoen, Minato 105-0011 Tokyo Prefecture',
    isFavorite: false,
  },
  {
    locationId: 6,
    locationName: '닌텐도 스토어',
    locationAddress: '4-chome 2-8, Shibakoen, Minato 105-0011 Tokyo Prefecture',
    isFavorite: false,
  },
];

export const dummy_schedules = [
  {
    id: 1,
    date: '2024-05-20',
    schedule: [
      {
        scheduleId: 1,
        time: '오전 09:00',
        location: '도쿄 디즈니랜드',
      },
      {
        scheduleId: 2,
        time: '오전 11:00',
        location: '이치란 라멘',
      },
      {
        scheduleId: 3,
        time: '오후 1:00',
        location: '쇼핑',
      },
      {
        scheduleId: 4,
        time: '오후 2:00',
        location: '도쿄 디즈니랜드',
      },
      {
        scheduleId: 5,
        time: '오후 3:00',
        location: '이치란 라멘',
      },
      {
        scheduleId: 6,
        time: '오후 6:00',
        location: '쇼핑',
      },
      {
        scheduleId: 7,
        time: '오후 9:00',
        location: '도쿄 디즈니랜드',
      },
      {
        scheduleId: 8,
        time: '오후 11:00',
        location: '이치란 라멘',
      },
    ],
  },
  {
    id: 2,
    date: '2024-05-21',
    schedule: [
      {
        scheduleId: 1,
        time: '오전 09:00',
        location: '도쿄타워',
      },
      {
        scheduleId: 2,
        time: '오전 11:00',
        location: '푸딩 먹으러 가기',
      },
      {
        scheduleId: 3,
        time: '오후 1:00',
        location: '다음 장소로 이동',
      },
    ],
  },
  {
    id: 3,
    date: '2024-05-22',
    schedule: [
      {
        scheduleId: 1,
        time: '오전 09:00',
        location: '신주쿠역에서 출발',
      },
      {
        scheduleId: 2,
        time: '오전 11:00',
        location: '타코야키 맛집',
      },
      {
        scheduleId: 3,
        time: '오후 1:00',
        location: '치이카와 팝업스토어',
      },
    ],
  },
  {
    id: 4,
    date: '2024-05-23',
    schedule: [
      {
        scheduleId: 1,
        time: '오전 09:00',
        location: '도쿄 디즈니랜드',
      },
      {
        scheduleId: 2,
        time: '오전 11:00',
        location: '이치란 라멘',
      },
      {
        scheduleId: 3,
        time: '오후 1:00',
        location: '쇼핑',
      },
    ],
  },
  {
    id: 5,
    date: '2024-05-24',
    schedule: [
      {
        scheduleId: 1,
        time: '오전 09:00',
        location: '도쿄 디즈니랜드',
      },
      {
        scheduleId: 2,
        time: '오전 11:00',
        location: '이치란 라멘',
      },
      {
        scheduleId: 3,
        time: '오후 1:00',
        location: '쇼핑',
      },
    ],
  },
  {
    id: 6,
    date: '2024-05-25',
    schedule: [
      {
        scheduleId: 1,
        time: '오전 09:00',
        location: '도쿄 디즈니랜드',
      },
      {
        scheduleId: 2,
        time: '오전 11:00',
        location: '이치란 라멘',
      },
      {
        scheduleId: 3,
        time: '오후 1:00',
        location: '쇼핑',
      },
    ],
  },
  {
    id: 7,
    date: '2024-05-26',
    schedule: [
      {
        scheduleId: 1,
        time: '오전 09:00',
        location: '도쿄 디즈니랜드',
      },
      {
        scheduleId: 2,
        time: '오전 11:00',
        location: '이치란 라멘',
      },
      {
        scheduleId: 3,
        time: '오후 1:00',
        location: '쇼핑',
      },
    ],
  },
];

export const dummy_attractions = [
  {
    id: 1,
    placeName: '메이지신궁',
    tag: '명소',
    detail: '도쿄에 위치한 문화 유산으로, 일본의 역사와 전통을 경험할 수 있는 아름다운 장소입니다.',
    location: { latitude: 37.78815, longitude: -122.4315 },
    coverImage: require('./assets/images/attraction/palace.png'),
    star: 3,
    reviews: [
      {
        id: 1,
        placeId: 1,
        comment: '좋았습니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 2,
        placeId: 1,
        comment: '좋았습니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 3,
        placeId: 1,
        comment: '좋았습니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 4,
        placeId: 1,
        comment: '좋았습니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
    ],
    tel: '00-000-000',
    createAt: new Date().getTime(),
  },
  {
    id: 2,
    placeName: '교파오 롯폰기',
    detail: '롯폰기에 위치한 교자 전문점, 직접 하이볼을 만들어 마실 수 있다.',
    location: { latitude: 37.78827, longitude: -122.4322 },
    tag: '맛집',
    coverImage: require('./assets/images/attraction/food.jpeg'),
    star: 3,
    reviews: [
      {
        id: 1,
        placeId: 2,
        comment: '맛있었어요. 주인분도 친절해요.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 2,
        placeId: 2,
        comment: '맛있었어요. 주인분도 친절해요.',
        createdAt: new Date().getTime(),
        star: 4,
      },
    ],
    tel: '00-000-000',
    createAt: new Date().getTime(),
  },
  {
    id: 3,
    placeName: '스크럼블 교차로',
    detail: '시부야 역 하치코 출구에서 여러 방향으로 한번에 건널 수 있도록 만들어진 시부야의 현관',
    location: { latitude: 37.78825, longitude: -122.4324 },
    tag: '명소',
    coverImage: require('./assets/images/attraction/scrumble.jpeg'),
    star: 3,
    reviews: [
      {
        id: 1,
        placeId: 3,
        comment: '사람이 많고 혼잡함.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 2,
        placeId: 3,
        comment: '사람이 많고 혼잡함.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 3,
        placeId: 3,
        comment: '사람이 많고 혼잡함.',
        createdAt: new Date().getTime(),
        star: 4,
      },
    ],
    tel: '00-000-000',
    createAt: new Date().getTime(),
  },
  {
    id: 4,
    placeName: '이치란 시부야점',
    detail: '진하고 부드러운 돈코츠 라멘으로 유명한 체인점',
    location: { latitude: 37.78822, longitude: -122.4322 },
    tag: '맛집',
    coverImage: require('./assets/images/attraction/food2.jpeg'),
    star: 3,
    reviews: [
      {
        id: 1,
        placeId: 4,
        comment: '웨이팅은 20분정도 해야 합니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 2,
        placeId: 4,
        comment: '웨이팅은 20분정도 해야 합니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
      {
        id: 3,
        placeId: 4,
        comment: '웨이팅은 20분정도 해야 합니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
    ],
    tel: '00-000-000',
    createAt: new Date().getTime(),
  },
  {
    id: 5,
    placeName: '우에노 공원',
    detail: '공원 숲속 아트 삼매경에 빠지고, 봄 벚꽃, 가을 낙엽으로 사계절이 아름다움을 즐기자.',
    location: { latitude: 37.7882, longitude: -122.4315 },
    tag: '명소',
    coverImage: require('./assets/images/attraction/park.jpeg'),
    star: 3,
    reviews: [
      {
        id: 1,
        placeId: 5,
        comment: '좋았습니다.',
        createdAt: new Date().getTime(),
        star: 4,
      },
    ],
    tel: '00-000-000',
    createAt: new Date().getTime(),
  },
];

export const DummyPlanData = [
  {
    id: '1',
    title: '뼈 J가 계획한 3박 4일 홍콩 여행',
    tags: ['축제', '쇼핑', '디즈니랜드'],
    likes: 16,
    bookmarks: 32,
  },
  {
    id: '2',
    title: '6박 7일 남큐슈 드라이브 여행 계획입니다.',
    tags: ['역사', '문화', '음식'],
    likes: 20,
    bookmarks: 15,
  },
  {
    id: '3',
    title: '어머니와 3박 4일 후쿠오카 계획 어떤가요',
    tags: ['역사', '문화', '음식'],
    likes: 30,
    bookmarks: 25,
  },
  {
    id: '4',
    title: '2박 3일 제주도 여행 일정',
    tags: ['자연', '힐링', '맛집'],
    likes: 45,
    bookmarks: 40,
  },
  {
    id: '5',
    title: '5박 6일 도쿄 디즈니랜드와 도쿄 시내 투어',
    tags: ['디즈니랜드', '쇼핑', '문화'],
    likes: 50,
    bookmarks: 60,
  },
  {
    id: '6',
    title: '3박 4일 대만 야시장 투어',
    tags: ['야시장', '음식', '쇼핑'],
    likes: 35,
    bookmarks: 28,
  },
  {
    id: '7',
    title: '7박 8일 유럽 배낭여행',
    tags: ['역사', '문화', '사진'],
    likes: 70,
    bookmarks: 85,
  },
  {
    id: '8',
    title: '4박 5일 방콕과 치앙마이 여행',
    tags: ['문화', '음식', '힐링'],
    likes: 55,
    bookmarks: 50,
  },
  {
    id: '9',
    title: '5박 6일 호주 시드니와 멜버른 여행',
    tags: ['자연', '문화', '쇼핑'],
    likes: 40,
    bookmarks: 35,
  },
  {
    id: '10',
    title: '3박 4일 베트남 다낭과 호이안 여행',
    tags: ['자연', '문화', '맛집'],
    likes: 60,
    bookmarks: 65,
  },
];

export const DummyDiaryData = [
  {
    id: '1',
    title: '오사카 마지막 날!',
    heartCount: 16,
    bookmarkCount: 32,
    image: require('./assets/icons/Explore/diaryimage.png'),
  },
  {
    id: '2',
    title: '몰디브 실시간',
    heartCount: 23,
    bookmarkCount: 15,
    image: require('./assets/images/myTrip/basicimage5.jpeg'),
  },
  {
    id: '3',
    title: '삿포로 왔어요!',
    heartCount: 4,
    bookmarkCount: 8,
    image: require('./assets/images/myTrip/basicimage7.jpeg'),
  },
  {
    id: '4',
    title: '풍경이 너무 이뻐서',
    heartCount: 14,
    bookmarkCount: 18,
    image: require('./assets/images/myTrip/basicimage2.jpeg'),
  },
];

export const scheduleData = {
  1: [
    { time: '오전 09:00', activity: '비행기 출발' },
    { time: '오전 11:00', activity: '호텔 체크인' },
    { time: '오후 12:30', activity: '점심 식사' },
    { time: '오후 02:00', activity: '침사추이 관광' },
    { time: '오후 04:00', activity: '스타페리 탑승' },
    { time: '오후 06:00', activity: '빅토리아 하버 야경' },
    { time: '오후 08:00', activity: '저녁 식사' },
    { time: '오후 10:00', activity: '호텔 귀환' },
  ],
  2: [
    { time: '오전 08:00', activity: '조식' },
    { time: '오전 09:00', activity: '홍콩 디즈니랜드 이동' },
    { time: '오전 10:00', activity: '홍콩 디즈니랜드 입장' },
    { time: '오후 01:00', activity: '점심 식사' },
    { time: '오후 03:00', activity: '디즈니랜드 퍼레이드' },
    { time: '오후 06:00', activity: '저녁 식사' },
    { time: '오후 08:00', activity: '디즈니랜드 불꽃놀이' },
    { time: '오후 10:00', activity: '호텔 귀환' },
  ],
  3: [
    { time: '오전 09:00', activity: '빅토리아 피크 이동' },
    { time: '오전 10:00', activity: '피크트램 탑승' },
    { time: '오전 11:00', activity: '빅토리아 피크 관광' },
    { time: '오후 12:30', activity: '점심 식사' },
    { time: '오후 02:00', activity: '센트럴 탐방' },
    { time: '오후 04:00', activity: '란콰이퐁 이동' },
    { time: '오후 06:00', activity: '저녁 식사' },
    { time: '오후 08:00', activity: '란콰이퐁 야경' },
    { time: '오후 10:00', activity: '호텔 귀환' },
  ],
  4: [
    { time: '오전 08:00', activity: '아침 운동' },
    { time: '오전 09:00', activity: '조식' },
    { time: '오전 10:00', activity: '마카오 페리 이동' },
    { time: '오전 11:00', activity: '마카오 관광' },
    { time: '오후 01:00', activity: '점심 식사' },
    { time: '오후 03:00', activity: '마카오 타워' },
    { time: '오후 05:00', activity: '호텔 체크아웃' },
    { time: '오후 06:00', activity: '공항 이동' },
    { time: '오후 09:00', activity: '비행기 출발' },
  ],
};
export const dummy_event = [
  {
    id: 1,
    date: '2024-05-03',
    events: [
      {
        eventId: 1,
        eventName: '구라야미 마쓰리',
        eventDuration: '2024-05-03 ~ 2024-05-06',
        detail:
          '오쿠니타마 신사에서 거행되는 이 축제는 신위가마 순행이 밤에 이루어진다 하여 ‘구라야미 마쓰리(어둠 축제)’라 불리고 있습니다.',
      },
      {
        eventId: 2,
        eventName: '구라야미 마쓰리',
        eventDuration: '2024-05-03 ~ 2024-05-06',
        detail:
          '오쿠니타마 신사에서 거행되는 이 축제는 신위가마 순행이 밤에 이루어진다 하여 ‘구라야미 마쓰리(어둠 축제)’라 불리고 있습니다.',
      },
      {
        eventId: 3,
        eventName: '구라야미 마쓰리',
        eventDuration: '2024-05-03 ~ 2024-05-06',
        detail:
          '오쿠니타마 신사에서 거행되는 이 축제는 신위가마 순행이 밤에 이루어진다 하여 ‘구라야미 마쓰리(어둠 축제)’라 불리고 있습니다.',
      },
    ],
  },
  {
    id: 2,
    date: '2024-05-16',
    events: [
      {
        eventId: 1,
        eventName: '산자 마쓰리',
        eventDuration: '2024-05-16 ~ 2024-05-22',
        detail:
          '산자 마쓰리 축제는 아사쿠사의 유명한 센소지 절 창건과 관련된 세 사람을 모신 신사의 제례로, 매년 5월 중순에 3일간 열립니다. 인정미 넘치는 도쿄의 서민거리 분위기를 체험할 수 있는 절호의 기회입니다.',
      },
    ],
  },
  {
    id: 3,
    date: '2024-05-29',
    events: [
      {
        eventId: 1,
        eventName: '도쿄 디자인 페스타',
        eventDuration: '2024-05-29 ~ 2024-05-30',
        detail:
          '‘디자인 페스타’는 국제적인 아트와 디자인의 대규모 이벤트입니다. 도쿄 빅사이트에서 개최되는 이 행사에는 음악, 회화, 패션, 공예, 사진, 퍼포먼스 등 다양한 분야에서 활약하는 1만 명 이상의 아티스트들이 집결합니다.',
      },
    ],
  },
  {
    id: 4,
    date: '2024-06-13',
    events: [
      {
        eventId: 1,
        eventName: '아쓰타 축제',
        eventDuration: '2024-06-13 ~ 2024-06-20',
        detail:
          '등불 전시와 맛난 음식, 무용이 한데 어우러져 활기찬 분위기를 자아냅니다. 약 2,000년의 역사를 가진 신사에서 열리는 이 축제는 독특한 일본의 전통을 탐방할 훌륭한 기회입니다.',
      },
    ],
  },
];
