export const dummy_user = [
  {
    id: 1,
    name: '이가연',
    nickname: '테디베어1',
    profileImage: require('./assets/images/dummy/dummyProfile_1.png'),
    email: 'test1@test.com',
    password: 'password',
    bookmarkList: [],
    interestArea: 'japan',
  },
  {
    id: 2,
    name: '오정혁',
    nickname: '테디베어2',
    profileImage: require('./assets/images/dummy/dummyProfile_2.png'),
    email: 'test2@test.com',
    password: 'password',
    bookmarkList: [],
    interestArea: 'japan',
  },
  {
    id: 3,
    name: '우예인',
    nickname: '테디베어3',
    profileImage: require('./assets/images/dummy/dummyProfile_3.png'),
    email: 'test3@test.com',
    password: 'password',
    bookmarkList: [],
    interestArea: 'japan',
  },
  {
    id: 4,
    name: '한서흔',
    nickname: '테디베어4',
    profileImage: require('./assets/images/dummy/dummyProfile_4.png'),
    email: 'test4@test.com',
    password: 'password',
    bookmarkList: [],
    interestArea: 'japan',
  },
  {
    id: 5,
    name: '김동영',
    nickname: '테디베어8',
    profileImage: require('./assets/images/dummy/dummyProfile_5.png'),
    email: 'test5@test.com',
    password: 'password',
    bookmarkList: [],
    interestArea: 'japan',
  },
];

export const dummy_article = [
  {
    id: 1,
    title: '도쿄 3박 4일 계획표 평가 부탁드려요!',
    content:
      '안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요? 안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요? 안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?안녕하세요! 제가 다음 달에 처음으로 도쿄에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들',
    createdAt: new Date().getTime(),
    like: 1,
    bookmark: 1,
    userId: 1,
    tag: '질문',
  },
  {
    id: 2,
    title: '프랑스 3박 4일 계획표 평가 부탁드려요!',
    content:
      '안녕하세요! 제가 다음 달에 처음으로 프랑스에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-05-03 10:20').getTime(),
    like: 2,
    bookmark: 2,
    userId: 2,
    tag: '잡담',
  },
  {
    id: 3,
    title: '미국 3박 4일 계획표 평가 부탁드려요!',
    content:
      '안녕하세요! 제가 다음 달에 처음으로 미국에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-05-02 10:20').getTime(),
    like: 3,
    bookmark: 3,
    userId: 4,
    tag: '질문',
  },
  {
    id: 4,
    title: '독일 3박 4일 계획표 평가 부탁드려요!',
    content:
      '안녕하세요! 제가 다음 달에 처음으로 독일에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-05-01 10:20').getTime(),
    like: 4,
    bookmark: 4,
    userId: 3,
    tag: '질문',
  },
  {
    id: 5,
    title: '호주 3박 4일 계획표 평가 부탁드려요!',
    content:
      '안녕하세요! 제가 다음 달에 처음으로 호주에 가게 되었는데요.. 첫 해외여행이라 너무 떨립니다 ㅎㅎ 고수님들의 계획표 조언 부탁드려도 될까요?',
    createdAt: new Date('2024-04-15 10:20').getTime(),
    like: 5,
    bookmark: 5,
    userId: 4,
    tag: '질문',
  },
];

export const dummy_comment = [
  {
    id: 1,
    name: '도쿄타워',
    articleId: 1,
    content: '마지막날 일정이 좀 빡빡한 것 같아요?',
    like: 1,
    userId: 1,
    createdAt: new Date(),
  },
  {
    id: 2,
    name: '도쿄타워',
    articleId: 1,
    content: '마지막날 일정이 좀 빡빡한 것 같아요??',
    like: 5,
    userId: 1,
    createdAt: new Date('2024-05-18 10:20'),
  },
  {
    id: 3,
    name: '도쿄타워',
    articleId: 1,
    content: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 1,
    createdAt: new Date('2024-05-20 16:20'),
  },
  {
    id: 4,
    name: '도쿄타워',
    articleId: 1,
    content: '마지막날 일정이 좀 빡빡한 것 같아요???',
    like: 3,
    userId: 1,
    createdAt: new Date('2024-05-20 16:20'),
  },
];

export const dummy_meet = [
  {
    id: 1,
    location: { latitude: 37.78827, longitude: -122.4322 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    name: '도쿄최고',
    profileImage: require('./assets/images/dummy/dummyProfile_1.png'),
    category: 'impromptu',
    createAt: new Date(),
    meetingAt: new Date(),
  },
  {
    id: 2,
    location: { latitude: 37.78825, longitude: -122.4324 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    name: '도쿄최고',
    profileImage: require('./assets/images/dummy/dummyProfile_2.png'),
    category: 'impromptu',
    createAt: new Date(),
    meetingAt: new Date(),
  },
  {
    id: 3,
    location: { latitude: 37.7883, longitude: -122.432 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    profileImage: require('./assets/images/dummy/dummyProfile_3.png'),
    name: '도쿄최고',
    category: 'accompany',
    createAt: new Date(),
    meetingAt: new Date(),
  },
  {
    id: 4,
    location: { latitude: 37.78815, longitude: -122.4318 },
    address: '도쿄타워',
    title: '도쿄타워 같이 가실 분',
    content: '도쿄타워 야경 보고 같이 저녁 먹을 한국인 분들 구해요!',
    name: '도쿄최고',
    profileImage: require('./assets/images/dummy/dummyProfile_4.png'),
    category: 'impromptu',
    createAt: new Date(),
    meetingAt: new Date(),
  },
];

export const dummy_chat = [
  {
    id: 1,
    sendUserId: 5,
    receiveUserId: 4,
    chatList: [
      {
        id: 1,
        userId: 5,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:20'),
        isRead: true,
      },
      {
        id: 2,
        userId: 4,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:21'),
        isRead: true,
      },
      {
        id: 3,
        userId: 5,
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-18 10:22'),
        isRead: true,
      },
      {
        id: 4,
        userId: 4,
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-18 10:23'),
        isRead: true,
      },
      {
        id: 5,
        userId: 5,
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-18 10:24'),
        isRead: false,
      },
    ],
  },
  {
    id: 2,
    sendUserId: 5,
    receiveUserId: 3,
    chatList: [
      {
        id: 1,
        userId: 5,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:20'),
        isRead: true,
      },
      {
        id: 2,
        userId: 3,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:21'),
        isRead: true,
      },
      {
        id: 3,
        userId: 5,
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-18 10:22'),
        isRead: true,
      },
      {
        id: 4,
        userId: 3,
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-18 10:23'),
        isRead: true,
      },
      {
        id: 5,
        userId: 5,
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-18 10:24'),
        isRead: true,
      },
    ],
  },
  {
    id: 3,
    sendUserId: 5,
    receiveUserId: 2,
    chatList: [
      {
        id: 1,
        userId: 5,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:20'),
        isRead: true,
      },
      {
        id: 2,
        userId: 2,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:21'),
        isRead: true,
      },
      {
        id: 3,
        userId: 5,
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-18 10:22'),
        isRead: true,
      },
      {
        id: 4,
        userId: 2,
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-18 10:23'),
        isRead: true,
      },
      {
        id: 5,
        userId: 5,
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-18 10:24'),
        isRead: true,
      },
    ],
  },
  {
    id: 4,
    sendUserId: 1,
    receiveUserId: 5,
    chatList: [
      {
        id: 1,
        userId: 1,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:20'),
        isRead: true,
      },
      {
        id: 2,
        userId: 5,
        text: '안녕하세요',
        createdAt: new Date('2024-05-18 10:21'),
        isRead: true,
      },
      {
        id: 3,
        userId: 1,
        text: '올라온 동행글 보고 연락했어요. 아직도 동행 구하시나요?',
        createdAt: new Date('2024-05-18 10:22'),
        isRead: true,
      },
      {
        id: 4,
        userId: 5,
        text: '네 아직 못구했어요 ㅠㅠ ',
        createdAt: new Date('2024-05-18 10:23'),
        isRead: true,
      },
      {
        id: 5,
        userId: 1,
        text: '그럼 저랑 같이 가실래요?',
        createdAt: new Date('2024-05-18 10:24'),
        isRead: true,
      },
    ],
  },
];
